// Code generated by genx:code DO NOT EDIT.
package confpulsar

import (
	"fmt"
)

func (e ecode) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[confpulsar.ecode:%d] unknown", e)
	case ECODE_UNDEFINED:
		return "[confpulsar.ecode:0] undefined"
	case ECODE__PARSE_MESSAGE:
		return "[confpulsar.ecode:1] failed to parse message"
	case ECODE__HANDLER_PANICKED:
		return "[confpulsar.ecode:2] subscriber handler panicked"
	case ECODE__SUBSCRIPTION_CANCELED:
		return "[confpulsar.ecode:3] subscription canceled"
	case ECODE__CLIENT_CLOSED:
		return "[confpulsar.ecode:4] client closed"
	case ECODE__SUBSCRIBER_CLOSED:
		return "[confpulsar.ecode:5] subscriber closed"
	case ECODE__PUBLISHER_CLOSED:
		return "[confpulsar.ecode:6] publisher closed"
	}
}
