// Code generated by genx:doc DO NOT EDIT.
package confpulsar

import (
	"github.com/xoctopus/x/docx"
)

func (v *Endpoint) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Endpoint":
			return []string{}, true
		}
		if doc, ok := docx.Of(&v.Endpoint, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"pulsar component endpoint"}, true
}

func (v *PulsarOption) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "OperationTimeout":
			return []string{}, true
		case "ConnTimeout":
			return []string{}, true
		case "KeepAliveInterval":
			return []string{}, true
		case "MaxConnector":
			return []string{}, true
		case "MaxPending":
			return []string{}, true
		case "MaxBatching":
			return []string{}, true
		}
		return []string{}, false
	}
	return []string{"presents pulsar client options"}, true
}

func (v *scheme) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *pubOption) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *subOption) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *subscriber) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}
