// Code generated by genx:enum@v0.3.0 DO NOT EDIT.
package confethcli

import (
	"bytes"
	"database/sql/driver"
	"fmt"

	"github.com/xoctopus/x/enumx"
)

var _ enumx.Enum[EthChainID] = (*EthChainID)(nil)

// ParseEthChainID parse EthChainID from key
func ParseEthChainID(key string) (EthChainID, error) {
	switch key {
	case "ETH":
		return ETH_CHAIN_ID__ETH, nil
	case "BSC":
		return ETH_CHAIN_ID__BSC, nil
	case "POLYGON":
		return ETH_CHAIN_ID__POLYGON, nil
	case "ARBITRUM":
		return ETH_CHAIN_ID__ARBITRUM, nil
	case "OPTIMISM":
		return ETH_CHAIN_ID__OPTIMISM, nil
	case "AVALANCHE":
		return ETH_CHAIN_ID__AVALANCHE, nil
	case "BASE":
		return ETH_CHAIN_ID__BASE, nil
	case "TRON":
		return ETH_CHAIN_ID__TRON, nil
	case "SEPOLIA":
		return ETH_CHAIN_ID__SEPOLIA, nil
	case "BSC_TESTNET":
		return ETH_CHAIN_ID__BSC_TESTNET, nil
	default:
		var v EthChainID
		if _, err := fmt.Sscanf(key, "UNKNOWN_%d", &v); err != nil {
			return v, nil
		}
		return ETH_CHAIN_ID_UNKNOWN, enumx.ParseErrorFor[EthChainID](key)
	}
}

// EnumValues implements enumx.CanBeEnum
func (EthChainID) EnumValues() []any {
	return []any{
		ETH_CHAIN_ID__ETH,
		ETH_CHAIN_ID__BSC,
		ETH_CHAIN_ID__POLYGON,
		ETH_CHAIN_ID__ARBITRUM,
		ETH_CHAIN_ID__OPTIMISM,
		ETH_CHAIN_ID__AVALANCHE,
		ETH_CHAIN_ID__BASE,
		ETH_CHAIN_ID__TRON,
		ETH_CHAIN_ID__SEPOLIA,
		ETH_CHAIN_ID__BSC_TESTNET,
	}
}

// Values returns enum value list of EthChainID
func (EthChainID) Values() []EthChainID {
	return []EthChainID{
		ETH_CHAIN_ID__ETH,
		ETH_CHAIN_ID__BSC,
		ETH_CHAIN_ID__POLYGON,
		ETH_CHAIN_ID__ARBITRUM,
		ETH_CHAIN_ID__OPTIMISM,
		ETH_CHAIN_ID__AVALANCHE,
		ETH_CHAIN_ID__BASE,
		ETH_CHAIN_ID__TRON,
		ETH_CHAIN_ID__SEPOLIA,
		ETH_CHAIN_ID__BSC_TESTNET,
	}
}

// String returns v's string as key
func (v EthChainID) String() string {
	switch v {
	case ETH_CHAIN_ID__ETH:
		return "ETH"
	case ETH_CHAIN_ID__BSC:
		return "BSC"
	case ETH_CHAIN_ID__POLYGON:
		return "POLYGON"
	case ETH_CHAIN_ID__ARBITRUM:
		return "ARBITRUM"
	case ETH_CHAIN_ID__OPTIMISM:
		return "OPTIMISM"
	case ETH_CHAIN_ID__AVALANCHE:
		return "AVALANCHE"
	case ETH_CHAIN_ID__BASE:
		return "BASE"
	case ETH_CHAIN_ID__TRON:
		return "TRON"
	case ETH_CHAIN_ID__SEPOLIA:
		return "SEPOLIA"
	case ETH_CHAIN_ID__BSC_TESTNET:
		return "BSC_TESTNET"
	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

// Text returns the description as for human reading
func (v EthChainID) Text() string {
	switch v {
	case ETH_CHAIN_ID__ETH:
		return "Ethereum Mainnet"
	case ETH_CHAIN_ID__BSC:
		return "BNB Smart Chain"
	case ETH_CHAIN_ID__POLYGON:
		return "Polygon PoS"
	case ETH_CHAIN_ID__ARBITRUM:
		return "Arbitrum One"
	case ETH_CHAIN_ID__OPTIMISM:
		return "OP Mainnet"
	case ETH_CHAIN_ID__AVALANCHE:
		return "Avalanche C-Chain"
	case ETH_CHAIN_ID__BASE:
		return "Base"
	case ETH_CHAIN_ID__TRON:
		return "Tron Mainnet"
	case ETH_CHAIN_ID__SEPOLIA:
		return "Sepolia"
	case ETH_CHAIN_ID__BSC_TESTNET:
		return "BSC Testnet"
	default:
		return v.String()
	}
}

// IsZero checks if v is zero
func (v EthChainID) IsZero() bool {
	return v == ETH_CHAIN_ID_UNKNOWN
}

// MarshalText implements encoding.TextMarshaler
func (v EthChainID) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (v *EthChainID) UnmarshalText(data []byte) error {
	vv, err := ParseEthChainID(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

// Value implements driver.Valuer
func (v EthChainID) Value() (driver.Value, error) {
	offset := 0
	if drv, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = drv.Offset()
	}
	return int64(v) + int64(offset), nil
}

// Scan implements sql.Scanner
func (v *EthChainID) Scan(src any) error {
	offset := 0
	if offsetter, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = offsetter.Offset()
	}
	i, err := enumx.Scan(src, offset)
	if err != nil {
		return err
	}
	*v = EthChainID(i)
	return nil
}
