package confws

// Error confws 错误码.
// +genx:code
// @code domain=CONFWS
type Error int8

const (
	ERROR_UNDEFINED Error = iota
	ERROR__ENDPOINT_NOT_INITIALIZED
	ERROR__ENDPOINT_INITIALIZED
	ERROR__SERVER_CLOSED
	ERROR__MISSING_REQUIRED_HOOKS
	ERROR__TOO_MANY_CONNECTION
	ERROR__CONNECTION_CALLBACK_FAILED
	ERROR__FAILED_TO_LISTENING
	ERROR__FAILED_TO_REGISTER_CLIENT
	ERROR__FAILED_TO_UPGRADE
	ERROR__CLIENT_CLOSED
	ERROR__CLIENT_IDLE_TIMEOUT
	ERROR__READ_ON_NON_PULL_CLIENT
)
