// Code generated by genx:code@v0.3.8 DO NOT EDIT.
package confpulsar

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[CONFPULSAR::ERROR:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[CONFPULSAR::ERROR:0] undefined"
	case ERROR__CLI_CLOSED:
		return "[CONFPULSAR::ERROR:1] client closed"
	case ERROR__CLI_INIT_ERROR:
		return "[CONFPULSAR::ERROR:2] client init failed"
	case ERROR__SUB_CLOSED:
		return "[CONFPULSAR::ERROR:3] subscriber closed"
	case ERROR__SUB_BOOTED:
		return "[CONFPULSAR::ERROR:4] subscriber is already booted"
	case ERROR__SUB_HANDLER_PANICKED:
		return "[CONFPULSAR::ERROR:5] subscriber handler panicked"
	case ERROR__SUB_UNSUBSCRIBED:
		return "[CONFPULSAR::ERROR:6] subscriber unsubscribed"
	case ERROR__PUB_CLOSED:
		return "[CONFPULSAR::ERROR:7] publisher closed"
	case ERROR__PUB_INVALID_MESSAGE:
		return "[CONFPULSAR::ERROR:8] publisher got invalid message"
	}
}
