// Code generated by genx:enum DO NOT EDIT.
package confpulsar

import (
	"bytes"
	"database/sql/driver"
	"fmt"

	"github.com/xoctopus/x/enumx"
)

var _ enumx.Enum[ExtraKind] = (*ExtraKind)(nil)

// ParseExtraKind parse ExtraKind from key
func ParseExtraKind(key string) (ExtraKind, error) {
	switch key {
	case "LAST_SEQUENCE_ID":
		return EXTRA_KIND__LAST_SEQUENCE_ID, nil
	case "DELIVERY_DELAYED":
		return EXTRA_KIND__DELIVERY_DELAYED, nil
	default:
		var v ExtraKind
		if _, err := fmt.Sscanf(key, "UNKNOWN_%d", &v); err != nil {
			return v, nil
		}
		return EXTRA_KIND_UNKNOWN, enumx.ParseErrorFor[ExtraKind](key)
	}
}

// Values returns enum value list of ExtraKind
func (ExtraKind) Values() []ExtraKind {
	return []ExtraKind{
		EXTRA_KIND__LAST_SEQUENCE_ID,
		EXTRA_KIND__DELIVERY_DELAYED,
	}
}

// String returns v's string as key
func (v ExtraKind) String() string {
	switch v {
	case EXTRA_KIND__LAST_SEQUENCE_ID:
		return "LAST_SEQUENCE_ID"
	case EXTRA_KIND__DELIVERY_DELAYED:
		return "DELIVERY_DELAYED"
	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

// Text returns the description as for human reading
func (v ExtraKind) Text() string {
	switch v {
	case EXTRA_KIND__LAST_SEQUENCE_ID:
		return "LAST_SEQUENCE_ID"
	case EXTRA_KIND__DELIVERY_DELAYED:
		return "DELIVERY_DELAYED"
	default:
		return v.String()
	}
}

// IsZero checks if v is zero
func (v ExtraKind) IsZero() bool {
	return v == EXTRA_KIND_UNKNOWN
}

// MarshalText implements encoding.TextMarshaler
func (v ExtraKind) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (v *ExtraKind) UnmarshalText(data []byte) error {
	vv, err := ParseExtraKind(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

// Value implements driver.Valuer
func (v ExtraKind) Value() (driver.Value, error) {
	offset := 0
	if drv, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = drv.Offset()
	}
	return int64(v) + int64(offset), nil
}

// Scan implements sql.Scanner
func (v *ExtraKind) Scan(src any) error {
	offset := 0
	if offsetter, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = offsetter.Offset()
	}
	i, err := enumx.Scan(src, offset)
	if err != nil {
		return err
	}
	*v = ExtraKind(i)
	return nil
}
