// Code generated by genx:doc DO NOT EDIT.
package confpulsar

import (
	"cgtech.gitlab.com/saitox/x/docx"
)

func (v *Endpoint) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Endpoint":
			return []string{}, true
		case "ResourceManager":
			return []string{}, true
		}
		if doc, ok := docx.Of(&v.Endpoint, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.ResourceManager, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"pulsar component endpoint"}, true
}

func (v *consumer) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *producer) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *Error) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"presents error codes for confpulsar"}, true
}

func (v *producerMessage) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ProducerMessage":
			return []string{}, true
		}
		if doc, ok := docx.Of(&v.ProducerMessage, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *consumerMessage) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Message":
			return []string{}, true
		}
		if doc, ok := docx.Of(&v.Message, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *Option) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "DisablePersistence":
			return []string{"[TOPIC] denotes topic scheme. default is \"persistent\"", "eg:", "persistent://<tenant>/[<cluster>/]<namespace>/topic", "non-persistent://<tenant>/[<cluster>/]<namespace>/topic"}, true
		case "Tenant":
			return []string{"[TOPIC] represents the top-level Pulsar tenant."}, true
		case "Cluster":
			return []string{"[TOPIC] denotes target cluster name of client connection"}, true
		case "Namespace":
			return []string{"[TOPIC] represents the logical domain under a tenant."}, true
		case "ConnectionTimeout":
			return []string{"[Client] establishment timeout"}, true
		case "ConnectionMaxIdleTime":
			return []string{"[Client] release the connection if it is not", "used for more than ConnectionMaxIdleTime. default is 30 minutes"}, true
		case "OperationTimeout":
			return []string{"[Client] producer-create, subscribe and unsubscribe", "operations will be retried until this interval"}, true
		case "KeepAliveInterval":
			return []string{"[Client] the ping send and check interval"}, true
		case "MaxConnectionsPerBroker":
			return []string{"[Client] max connections to a single broker"}, true
		case "SendTimeout":
			return []string{"[PUB] specifies the timeout for a message from sent to", "acknowledged by the server"}, true
		case "DisableBlockIfQueueFull":
			return []string{"[PUB] controls whether Send and SendAsync block", "when producer's message queue is full."}, true
		case "MaxPendingMessages":
			return []string{"[PUB] specifies the max size of the queue holding"}, true
		case "DisableCompress":
			return []string{"[PUB] specifies if disable message compression, if it is", "enabled use LZ4 compress type"}, true
		case "BatchingMaxMessages":
			return []string{"[PUB] specifies the max messages permitted in a batch"}, true
		case "DisablePubShared":
			return []string{"[PUB] if disabled, publisher is required exclusive access", "for producer. failed immediately if there's already a producer connected."}, true
		case "EnableSubShared":
			return []string{"[SUB] if disabled, there can be only 1 consumer on the same", "topic with the same subscription name"}, true
		case "EnableRetryNack":
			return []string{"[SUB] if enabled, NACKed message will be redelivered after", "NackRetryInterval max MaxNackRetry times. if reached MaxNackRetry times,", "the message filled to global DLQ"}, true
		case "NackRetryInterval":
			return []string{"[SUB] retry nack message interval"}, true
		case "MaxNackRetry":
			return []string{"[SUB] max retry times for nack message"}, true
		case "WorkerSize":
			return []string{"defines the concurrency level for message consumption.", "Behavior based on ConsumeMode:", "eg:", "- mq.GlobalOrdered: Forced to 1 to ensure strict sequential processing.", "- mq.PartitionOrdered: Messages are dispatched to specific workers based on", "a hash of the partition key, ensuring order within the same key.", "- mq.Concurrent: messages are distributed across all workers (e.g., round-robin)", "to maximize throughput."}, true
		case "WorkerBufferSize":
			return []string{"[SUB] will prefetch message from broker for improves", "consumption throughput and reducing wait"}, true
		}
		return []string{}, false
	}
	return []string{"presents pulsar client options and default pub/sub options. it can be", "overridden by option applier when call Endpoint.Publish and Endpoint.Subscribe"}, true
}

func (v *PubOption) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *SubOption) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *nackBackoffPolicy) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}
