services:
  redis:
    image: redis:latest
    container_name: redis_confx
    platform: linux/amd64
    restart: always
    command: redis-server --requirepass "123456"
    ports:
      - "16379:6379"

  pulsar:
    image: apachepulsar/pulsar:4.1.0
    container_name: pulsar_confx
    platform: linux/amd64
    restart: always
    command: bin/pulsar standalone
    ports:
      - "16650:6650"
      - "18080:8080"

  mysql:
    image: mysql:latest
    container_name: mysql_confx
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_USER: "user"
      MYSQL_PASSWORD: ""
      TZ: "Asia/Shanghai"
    ports:
      - "13306:3306"
    volumes:
      - ./scripts/mysql.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/xxl.sql:/docker-entrypoint-initdb.d/init_xxl.sql
    restart: always

  postgres:
    image: postgres:18
    container_name: postgres_confx
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: "Asia/Shanghai"
    ports:
      - "15432:5432"
    volumes:
      - ./scripts/postgres.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  pulsar-manager:
    image: apachepulsar/pulsar-manager:v0.4.0
    container_name: pulsar_manager_confx
    platform: linux/amd64
    restart: always
    depends_on:
      - pulsar
    ports:
      - "19527:9527" # Web UI
      - "17750:7750" # Manager Backend API
    environment:
      - SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties
      - USERNAME=admin
      - PASSWORD=admin123

  pulsar-init-helper:
    image: curlimages/curl:latest
    container_name: pulsar_init_helper_confx
    depends_on:
      - pulsar
      - pulsar-manager
    volumes:
      - ./scripts/pulsar-entrypoint.sh:/pulsar-entrypoint.sh
    entrypoint: [ "/bin/sh", "/pulsar-entrypoint.sh" ]

  xxl-job-admin:
    image: xuxueli/xxl-job-admin:3.2.0
    container_name: xxl_confx
    platform: linux/amd64
    restart: always
    depends_on:
      - mysql
    environment:
      PARAMS: >-
        --spring.datasource.username=root
        --spring.datasource.password=
        --xxl.job.accessToken=l6MOJuZ12RKzfaM1
        --xxl.job.logpath=/data/xxl-job
        --xxl.job.logretentiondays=1
      SPRING_DATASOURCE_URL: >-
        jdbc:mysql://mysql:3306/xxl_job
        ?useUnicode=true
        &characterEncoding=UTF-8
        &autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      XXL_JOB_LOGIN_USERNAME: admin
      XXL_JOB_LOGIN_PASSWORD: xxljob
      XXL_JOB_I18N: en
      SERVER_PORT: 8081
    ports:
      - "18081:8081"

  doris-manager:
    image: apache/doris:fe-4.0.0
    container_name: doris_manager_confx
    hostname: doris_manager_confx
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010
      - FE_ID=1
      - PRIORITY_NETWORKS=172.20.80.0/24
    ports:
      - "8030:8030" # web
      - "9030:9030" # mysql client
    networks:
      doris_net:
        ipv4_address: 172.20.80.2

  doris:
    image: apache/doris:be-4.0.0
    container_name: doris_confx
    hostname: doris_confx
    depends_on:
      - doris-manager
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010
      - BE_ADDR=172.20.80.2:9050
      - PRIORITY_NETWORKS=172.20.80.0/24
    ports:
      - "8040:8040"
    ulimits:
      nofile:
        soft: 200000
        hard: 200000
    networks:
      doris_net:
        ipv4_address: 172.20.80.3

  doris-init:
    image: mysql:latest
    container_name: doris_init
    depends_on:
      - doris-manager
      - doris
    networks:
      - doris_net
    volumes:
      - ./scripts/doris.sh:/doris.sh
    entrypoint: [ "/bin/bash", "/doris.sh" ]

networks:
  doris_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.80.0/24