// Code generated by genx:enum DO NOT EDIT.
package enums

import (
	"bytes"
	"database/sql/driver"
	"fmt"

	"github.com/xoctopus/x/enumx"
)

var _ enumx.Enum[BlockStrategy] = (*BlockStrategy)(nil)

// ParseBlockStrategy parse BlockStrategy from key
func ParseBlockStrategy(key string) (BlockStrategy, error) {
	switch key {
	case "SERIAL_EXECUTION":
		return BLOCK_STRATEGY__SERIAL_EXECUTION, nil
	case "DISCARD_LATER":
		return BLOCK_STRATEGY__DISCARD_LATER, nil
	case "COVER_EARLY":
		return BLOCK_STRATEGY__COVER_EARLY, nil
	default:
		var v BlockStrategy
		if _, err := fmt.Sscanf(key, "UNKNOWN_%d", &v); err != nil {
			return v, nil
		}
		return BLOCK_STRATEGY_UNKNOWN, enumx.ParseErrorFor[BlockStrategy](key)
	}
}

// Values returns enum value list of BlockStrategy
func (BlockStrategy) Values() []BlockStrategy {
	return []BlockStrategy{
		BLOCK_STRATEGY__SERIAL_EXECUTION,
		BLOCK_STRATEGY__DISCARD_LATER,
		BLOCK_STRATEGY__COVER_EARLY,
	}
}

// String returns v's string as key
func (v BlockStrategy) String() string {
	switch v {
	case BLOCK_STRATEGY__SERIAL_EXECUTION:
		return "SERIAL_EXECUTION"
	case BLOCK_STRATEGY__DISCARD_LATER:
		return "DISCARD_LATER"
	case BLOCK_STRATEGY__COVER_EARLY:
		return "COVER_EARLY"
	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

// Text returns the description as for human reading
func (v BlockStrategy) Text() string {
	switch v {
	case BLOCK_STRATEGY__SERIAL_EXECUTION:
		return "SERIAL_EXECUTION"
	case BLOCK_STRATEGY__DISCARD_LATER:
		return "DISCARD_LATER"
	case BLOCK_STRATEGY__COVER_EARLY:
		return "COVER_EARLY"
	default:
		return v.String()
	}
}

// IsZero checks if v is zero
func (v BlockStrategy) IsZero() bool {
	return v == BLOCK_STRATEGY_UNKNOWN
}

// MarshalText implements encoding.TextMarshaler
func (v BlockStrategy) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (v *BlockStrategy) UnmarshalText(data []byte) error {
	vv, err := ParseBlockStrategy(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

// Value implements driver.Valuer
func (v BlockStrategy) Value() (driver.Value, error) {
	offset := 0
	if drv, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = drv.Offset()
	}
	return int64(v) + int64(offset), nil
}

// Scan implements sql.Scanner
func (v *BlockStrategy) Scan(src any) error {
	offset := 0
	if offsetter, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = offsetter.Offset()
	}
	i, err := enumx.Scan(src, offset)
	if err != nil {
		return err
	}
	*v = BlockStrategy(i)
	return nil
}
