// Code generated by genx:enum DO NOT EDIT.
package enums

import (
	"bytes"
	"database/sql/driver"
	"fmt"

	"github.com/xoctopus/x/enumx"
)

var _ enumx.Enum[GlueType] = (*GlueType)(nil)

// ParseGlueType parse GlueType from key
func ParseGlueType(key string) (GlueType, error) {
	switch key {
	case "BEAN":
		return GLUE_TYPE__BEAN, nil
	case "GLUE_GROOVY":
		return GLUE_TYPE__GLUE_GROOVY, nil
	case "GLUE_SHELL":
		return GLUE_TYPE__GLUE_SHELL, nil
	case "GLUE_PYTHON":
		return GLUE_TYPE__GLUE_PYTHON, nil
	case "GLUE_PHP":
		return GLUE_TYPE__GLUE_PHP, nil
	case "GLUE_NODEJS":
		return GLUE_TYPE__GLUE_NODEJS, nil
	case "GLUE_POWERSHELL":
		return GLUE_TYPE__GLUE_POWERSHELL, nil
	default:
		var v GlueType
		if _, err := fmt.Sscanf(key, "UNKNOWN_%d", &v); err != nil {
			return v, nil
		}
		return GLUE_TYPE_UNKNOWN, enumx.ParseErrorFor[GlueType](key)
	}
}

// Values returns enum value list of GlueType
func (GlueType) Values() []GlueType {
	return []GlueType{
		GLUE_TYPE__BEAN,
		GLUE_TYPE__GLUE_GROOVY,
		GLUE_TYPE__GLUE_SHELL,
		GLUE_TYPE__GLUE_PYTHON,
		GLUE_TYPE__GLUE_PHP,
		GLUE_TYPE__GLUE_NODEJS,
		GLUE_TYPE__GLUE_POWERSHELL,
	}
}

// String returns v's string as key
func (v GlueType) String() string {
	switch v {
	case GLUE_TYPE__BEAN:
		return "BEAN"
	case GLUE_TYPE__GLUE_GROOVY:
		return "GLUE_GROOVY"
	case GLUE_TYPE__GLUE_SHELL:
		return "GLUE_SHELL"
	case GLUE_TYPE__GLUE_PYTHON:
		return "GLUE_PYTHON"
	case GLUE_TYPE__GLUE_PHP:
		return "GLUE_PHP"
	case GLUE_TYPE__GLUE_NODEJS:
		return "GLUE_NODEJS"
	case GLUE_TYPE__GLUE_POWERSHELL:
		return "GLUE_POWERSHELL"
	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

// Text returns the description as for human reading
func (v GlueType) Text() string {
	switch v {
	case GLUE_TYPE__BEAN:
		return "BEAN"
	case GLUE_TYPE__GLUE_GROOVY:
		return "GLUE_GROOVY"
	case GLUE_TYPE__GLUE_SHELL:
		return "GLUE_SHELL"
	case GLUE_TYPE__GLUE_PYTHON:
		return "GLUE_PYTHON"
	case GLUE_TYPE__GLUE_PHP:
		return "GLUE_PHP"
	case GLUE_TYPE__GLUE_NODEJS:
		return "GLUE_NODEJS"
	case GLUE_TYPE__GLUE_POWERSHELL:
		return "GLUE_POWERSHELL"
	default:
		return v.String()
	}
}

// IsZero checks if v is zero
func (v GlueType) IsZero() bool {
	return v == GLUE_TYPE_UNKNOWN
}

// MarshalText implements encoding.TextMarshaler
func (v GlueType) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (v *GlueType) UnmarshalText(data []byte) error {
	vv, err := ParseGlueType(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

// Value implements driver.Valuer
func (v GlueType) Value() (driver.Value, error) {
	offset := 0
	if drv, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = drv.Offset()
	}
	return int64(v) + int64(offset), nil
}

// Scan implements sql.Scanner
func (v *GlueType) Scan(src any) error {
	offset := 0
	if offsetter, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = offsetter.Offset()
	}
	i, err := enumx.Scan(src, offset)
	if err != nil {
		return err
	}
	*v = GlueType(i)
	return nil
}
