// Code generated by genx:doc DO NOT EDIT.
package cmds

func (v *Server) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Debug":
			return []string{"enable debug mode 1-enable"}, true
		case "LogLevel":
			return []string{"set log level [debug info warn error]"}, true
		case "Port":
			return []string{"server listen port"}, true
		}
		return []string{}, false
	}
	return []string{"start an echo server"}, true
}

func (v *Version) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"output command version"}, true
}
