// Code generated by genx:code@v0.3.8 DO NOT EDIT.
package envx

import (
	"fmt"
)

func (e Code) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[ENVX::CODE:%d] unknown", e)
	case CODE_UNDEFINED:
		return "[ENVX::CODE:1] undefined"
	case CODE__DEC_INVALID_VALUE:
		return "[ENVX::CODE:2] cannot set value"
	case CODE__DEC_INVALID_VALUE_CANNOT_SET:
		return "[ENVX::CODE:3] nil value"
	case CODE__DEC_INVALID_MAP_KEY_TYPE:
		return "[ENVX::CODE:4] invalid map key type, expect alphabet string or positive integer"
	case CODE__DEC_FAILED_UNMARSHAL:
		return "[ENVX::CODE:5] failed to unmarshal"
	case CODE__ENC_INVALID_MAP_KEY_TYPE:
		return "[ENVX::CODE:6] invalid map key type, expect alphabet string or positive integer"
	case CODE__ENC_INVALID_MAP_KEY_VALUE:
		return "[ENVX::CODE:7] invalid map key value, expect alphabet string or positive integer"
	case CODE__ENC_INVALID_ENV_KEY:
		return "[ENVX::CODE:8] invalid env key, expect alphabet string"
	case CODE__ENC_FAILED_MARSHAL:
		return "[ENVX::CODE:9] failed to marshal"
	case CODE__ENC_DUPLICATE_GROUP_KEY:
		return "[ENVX::CODE:10] group key duplicated"
	}
}
