// Code generated by genx:code DO NOT EDIT.
package envx

import (
	"fmt"
)

func (e Code) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[envx.Error:%d] unknown", e)
	case CODE_UNDEFINED:
		return "[envx.Error:1] undefined"
	case CODE__DEC_INVALID_VALUE:
		return "[envx.Error:2] cannot set value"
	case CODE__DEC_INVALID_VALUE_CANNOT_SET:
		return "[envx.Error:3] nil value"
	case CODE__DEC_INVALID_MAP_KEY_TYPE:
		return "[envx.Error:4] invalid map key type, expect alphabet string or positive integer"
	case CODE__DEC_FAILED_UNMARSHAL:
		return "[envx.Error:5] failed to unmarshal"
	case CODE__ENC_INVALID_MAP_KEY_TYPE:
		return "[envx.Error:6] invalid map key type, expect alphabet string or positive integer"
	case CODE__ENC_INVALID_MAP_KEY_VALUE:
		return "[envx.Error:7] invalid map key value, expect alphabet string or positive integer"
	case CODE__ENC_INVALID_ENV_KEY:
		return "[envx.Error:8] invalid env key, expect alphabet string"
	case CODE__ENC_FAILED_MARSHAL:
		return "[envx.Error:9] failed to marshal"
	case CODE__ENC_DUPLICATE_GROUP_KEY:
		return "[envx.Error:10] group key duplicated"
	}
}
