// Code generated by genx:doc DO NOT EDIT.
package types

func (v *Duration) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"extends time.Duraiton for"}, true
}

func (v *Endpoint[Option]) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Address":
			return []string{"component connection endpoint address"}, true
		case "Auth":
			return []string{"support Endpoint auth info with username and password"}, true
		case "Option":
			return []string{"component Option. if no option use EndpointNoOption"}, true
		case "Cert":
			return []string{"X509KeyPair to support certification info"}, true
		}
		return []string{}, false
	}
	return []string{"a connectable endpoint", "Note options in url Param can override option"}, true
}

func (v *LivenessData) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Reachable":
			return []string{"if remote endpoint is reachable"}, true
		case "TTL":
			return []string{"probes ttl to remote endpoint"}, true
		case "Message":
			return []string{"result or extended message"}, true
		}
		return []string{}, false
	}
	return []string{"presents LivenessChecker result"}, true
}

func (v *Password) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"as a string underlying and implements SecurityStringer"}, true
}

func (v *Userinfo) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Username":
			return []string{}, true
		case "Password":
			return []string{}, true
		case "DecryptKeyEnv":
			return []string{"if not empty read key from env and decrypt password by AEC", "with ECB mode and PKCS7 padding. default env key is PASSWORD_DEC_KEY"}, true
		}
		return []string{}, false
	}
	return []string{"likes url.Userinfo but embed aes decryptor if DecryptKeyEnv is set.", "and implemented SecurityString to hide password"}, true
}
