// Code generated by genx:doc DO NOT EDIT.
package confredis

import (
	"github.com/xoctopus/x/docx"
)

func (v *Endpoint) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Endpoint":
			return []string{}, true
		}
		if doc, ok := docx.Of(&v.Endpoint, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"redis component endpoint"}, true
}

func (v *Option) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Prefix":
			return []string{}, true
		case "ConnTimeout":
			return []string{}, true
		case "WriteTimeout":
			return []string{}, true
		case "ReadTimeout":
			return []string{}, true
		case "KeepAlive":
			return []string{}, true
		case "MaxActive":
			return []string{}, true
		case "MaxIdle":
			return []string{}, true
		case "ClientName":
			return []string{}, true
		case "SkipTLSVerify":
			return []string{}, true
		case "Wait":
			return []string{}, true
		}
		return []string{}, false
	}
	return []string{"presents"}, true
}
