// Code generated by genx:code DO NOT EDIT.
package confxxl

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[confxxl.Error:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[confxxl.Error:0] undefined"
	case ERROR__XXL_INVALID_ACTION:
		return "[confxxl.Error:1] XXL_INVALID_ACTION"
	case ERROR__ENDPOINT_CLOSED:
		return "[confxxl.Error:2] ENDPOINT_CLOSED"
	case ERROR__EXECUTOR_CLOSED:
		return "[confxxl.Error:3] EXECUTOR_CLOSED"
	case ERROR__EXECUTOR_NOT_REGISTERED:
		return "[confxxl.Error:4] EXECUTOR_NOT_REGISTERED"
	case ERROR__EXECUTOR_REGISTER_FAILED:
		return "[confxxl.Error:5] EXECUTOR_REGISTER_FAILED"
	case ERROR__EXECUTOR_REGISTER_REMOVE_FAILED:
		return "[confxxl.Error:6] EXECUTOR_REGISTER_REMOVE_FAILED"
	case ERROR__EXECUTOR_CALLBACK_FAILED:
		return "[confxxl.Error:7] EXECUTOR_CALLBACK_FAILED"
	case ERROR__EXECUTOR_SCHEDULE_TIMEOUT:
		return "[confxxl.Error:8] EXECUTOR_SCHEDULE_TIMEOUT"
	case ERROR__JOB_MANAGER_CLOSED:
		return "[confxxl.Error:9] JOB_MANAGER_CLOSED"
	case ERROR__JOB_MANAGER_REGISTRY_CONFLICT:
		return "[confxxl.Error:10] JOB_MANAGER_REGISTRY_CONFLICT"
	case ERROR__JOB_NOT_REGISTERED:
		return "[confxxl.Error:11] JOB_NOT_REGISTERED"
	case ERROR__JOB_SCHEDULER_BUSY:
		return "[confxxl.Error:12] JOB_SCHEDULER_BUSY"
	case ERROR__JOB_PENDING_TASK_SKIP:
		return "[confxxl.Error:13] JOB_PENDING_TASK_SKIP"
	case ERROR__JOB_CLOSED:
		return "[confxxl.Error:14] job is closed"
	case ERROR__JOB_MANUAL_CLOSE:
		return "[confxxl.Error:15] job is closed by user"
	}
}
