package confxxl

// Error presents error codes for confxxl
// +genx:code
type Error int8

const (
	ERROR_UNDEFINED Error = iota
	ERROR__XXL_INVALID_ACTION
	ERROR__ENDPOINT_CLOSED
	ERROR__EXECUTOR_CLOSED
	ERROR__EXECUTOR_NOT_REGISTERED
	ERROR__EXECUTOR_REGISTER_FAILED
	ERROR__EXECUTOR_REGISTER_REMOVE_FAILED
	ERROR__EXECUTOR_CALLBACK_FAILED
	ERROR__EXECUTOR_SCHEDULE_TIMEOUT
	ERROR__JOB_MANAGER_CLOSED
	ERROR__JOB_MANAGER_REGISTRY_CONFLICT
	ERROR__JOB_NOT_REGISTERED
	ERROR__JOB_SCHEDULER_BUSY
	ERROR__JOB_PENDING_TASK_SKIP
	ERROR__JOB_CLOSED       // job is closed
	ERROR__JOB_MANUAL_CLOSE // job is closed by user
)
