listeners.tcp.default = 5672
listeners.ssl.default = 5671

ssl_options.cacertfile = /tls/ca.crt
ssl_options.certfile   = /tls/server.crt
ssl_options.keyfile    = /tls/server.key
ssl_options.verify     = verify_none
ssl_options.fail_if_no_peer_cert = false
