// Code generated by genx:code@v0.3.8 DO NOT EDIT.
package mq

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[MQ::ERROR:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[MQ::ERROR:0] undefined"
	case ERROR__CLI_CLOSED:
		return "[MQ::ERROR:1] client closed"
	case ERROR__CLI_INIT_ERROR:
		return "[MQ::ERROR:2] client init failed"
	case ERROR__SUB_CLOSED:
		return "[MQ::ERROR:3] subscriber closed"
	case ERROR__SUB_BOOTED:
		return "[MQ::ERROR:4] subscriber is already booted"
	case ERROR__SUB_HANDLER_PANICKED:
		return "[MQ::ERROR:5] subscriber handler panicked"
	case ERROR__SUB_PARSE_MESSAGE_ERROR:
		return "[MQ::ERROR:6] subscriber failed to parse message"
	case ERROR__SUB_UNSUBSCRIBED:
		return "[MQ::ERROR:7] subscriber unsubscribed"
	case ERROR__PUB_CLOSED:
		return "[MQ::ERROR:8] publisher closed"
	case ERROR__PUB_INVALID_MESSAGE:
		return "[MQ::ERROR:9] publisher got invalid message"
	}
}
