// Code generated by genx:code DO NOT EDIT.
package mq

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[mq.Error:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[mq.Error:0] undefined"
	case ERROR__CLI_CLOSED:
		return "[mq.Error:1] client closed"
	case ERROR__CLI_INIT_ERROR:
		return "[mq.Error:2] client init failed"
	case ERROR__SUB_CLOSED:
		return "[mq.Error:3] subscriber closed"
	case ERROR__SUB_BOOTED:
		return "[mq.Error:4] subscriber is already booted"
	case ERROR__SUB_HANDLER_PANICKED:
		return "[mq.Error:5] subscriber handler panicked"
	case ERROR__SUB_PARSE_MESSAGE_ERROR:
		return "[mq.Error:6] subscriber failed to parse message"
	case ERROR__SUB_UNSUBSCRIBED:
		return "[mq.Error:7] subscriber unsubscribed"
	case ERROR__PUB_CLOSED:
		return "[mq.Error:8] publisher closed"
	case ERROR__PUB_INVALID_MESSAGE:
		return "[mq.Error:9] publisher got invalid message"
	}
}
